import {RequestConfig} from "@core/models";

export const RequestsConfig: RequestConfig[] = [
  {pathTemplate: '/exam/', method: 'POST', loading: false, success: true, failure: true, catch: false},
  {pathTemplate: '/exam/', method: 'PUT', loading: false, success: true, failure: true, catch: false},
  {pathTemplate: '/exam/', method: 'GET', loading: true, success: false, failure: true, catch: false},
  {pathTemplate: '/exam/*/', method: 'GET', loading: true, success: false, failure: true, catch: false},
  {pathTemplate: '/exam/*/', method: 'DELETE', loading: true, success: true, failure: true, catch: false},
  {pathTemplate: '/exam/activation/', method: 'POST', loading: false, success: true, failure: true, catch: false},
  {pathTemplate: '/exam/correct/', method: 'POST', loading: false, success: true, failure: true, catch: false},
  {pathTemplate: '/exam/recreate/', method: 'POST', loading: true, success: true, failure: true, catch: false},
  {pathTemplate: '/preUpload/', method: 'POST', loading: false, success: false, failure: true, catch: false},
  {pathTemplate: '/upload/', method: 'POST', loading: false, success: false, failure: true, catch: false},
  {pathTemplate: '/upload-answer/', method: 'POST', loading: true, success: false, failure: true, catch: false},
  {pathTemplate: '/answer/*/finish/', method: 'GET', loading: true, success: false, failure: true, catch: false},
  {pathTemplate: '/answer/*/', method: 'GET', loading: false, success: false, failure: true, catch: false},
  {pathTemplate: '/answer/', method: 'POST', loading: true, success: true, failure: true, catch: false},
  {pathTemplate: '/user/whoami/', method: 'GET', loading: true, success: false, failure: true, catch: false},
  {pathTemplate: '/user/students/*/*', method: 'GET', loading: true, success: false, failure: true, catch: false},
  {pathTemplate: '/user/classes/', method: 'GET', loading: true, success: false, failure: true, catch: false},
  {pathTemplate: '/office/', method: 'POST', loading: true, success: true, failure: true, catch: false},
  {pathTemplate: '/office/*/*', method: 'GET', loading: true, success: false, failure: true, catch: false},
  {pathTemplate: '/tutorial/', method: 'POST', loading: true, success: true, failure: true, catch: false},
  {pathTemplate: '/tutorial/', method: 'PUT', loading: true, success: true, failure: true, catch: false},
  {pathTemplate: '/tutorial/', method: 'GET', loading: true, success: false, failure: true, catch: false},
  {pathTemplate: '/tutorial/*/', method: 'GET', loading: true, success: false, failure: true, catch: false},
  {pathTemplate: '/tutorial/*/', method: 'DELETE', loading: true, success: true, failure: true, catch: false},
  {pathTemplate: '/tutorial/comment/', method: 'POST', loading: true, success: true, failure: true, catch: false},
  {pathTemplate: '/tutorial/like/*/', method: 'GET', loading: true, success: true, failure: true, catch: false},
  {pathTemplate: '/tutorial/dislike/*/', method: 'GET', loading: true, success: true, failure: true, catch: false},
];
